version: '3.1'

services:
  backend:
    image: backend:latest

  forum-console:
    image: forum-console:latest
  
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: test
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    