version: '3.1'

services:
  backend:
    image: backend
    restart: always
    ports:
      - "3000:3000"
    links:
      - db:database
    environment:
      DB_HOST: database
      HOST: host.docker.internal
    build:
      context: backend
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:172.101.0.1"
#  forum-console:
#    image: forum-console
#    ports:
#      - "8080:80"
#    environment:
#      - NGINX_HOST=localhost
#      - NGINX_PORT=80
#    build:
#      context: frontend
#      dockerfile: Dockerfile
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: test
    volumes:
      - ./backend/postgresdb:/var/lib/postgresql/data
    expose:
      - 5432